In [52]:
import tensorflow as tf 
import tensorflow.keras as Keras 

In [53]:
fashion_data = Keras.datasets.fashion_mnist.load_data()

In [54]:
fashion_data

((array([[[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         ...,
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          ...,
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0]],
  
         [[0, 0, 0, ..., 0, 0, 0],
          [0, 0, 0, ..., 0, 0, 0

In [55]:
(X_train_full, y_train_full),(X_test, y_test) = fashion_data

In [56]:
X_train, y_train = X_train_full[:-5000], y_train_full[:-5000]
X_valid, y_valid = X_train_full[-5000:], y_train_full[-5000:]

In [57]:
X_train.shape

(55000, 28, 28)

In [58]:
X_valid.shape

(5000, 28, 28)

In [59]:
X_train , X_valid , X_test = X_train/255. , X_valid / 255. , X_test / 255.

In [60]:
class_names = ["T-shirt/top", "Trouser", "Pullover", "Dress", "Coat",
"Sandal", "Shirt", "Sneaker", "Bag", "Ankle boot"]

In [61]:
set(y_train)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [62]:
class_names[y_train[2]]

'T-shirt/top'

## neural network 

In [63]:
tf.random.set_seed(42)

In [64]:
model = Keras.Sequential([
Keras.layers.Input([28,28]),
Keras.layers.Flatten(),
Keras.layers.Dense(300, activation='relu'),
Keras.layers.Dense(100 , activation='relu'),
Keras.layers.Dense(10 , activation= 'softmax')
])


In [65]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_3 (Dense)             (None, 300)               235500    
                                                                 
 dense_4 (Dense)             (None, 100)               30100     
                                                                 
 dense_5 (Dense)             (None, 10)                1010      
                                                                 
Total params: 266,610
Trainable params: 266,610
Non-trainable params: 0
_________________________________________________________________


In [66]:
# tf.keras.utils.plot_model( 
#     model,
#     to_file='model.png',
#     show_shapes=False,
#     show_dtype=False,
#     show_layer_names=True,
#     rankdir='TB',
#     expand_nested=False,
#     dpi=96,
#     layer_range=None,
#     show_layer_activations=False,
#     show_trainable=False)

In [67]:
model.layers

In [68]:
hidden1 = model.layers[1]

In [69]:
hidden1.name

'dense_3'

In [70]:
model.get_layer('dense') is hidden1

ValueError: No such layer: dense. Existing layers are [<keras.layers.core.flatten.Flatten object at 0x000002AE4B86E3A0>, <keras.layers.core.dense.Dense object at 0x000002AE4B86C0D0>, <keras.layers.core.dense.Dense object at 0x000002AE4B86CFA0>, <keras.layers.core.dense.Dense object at 0x000002AE4B86C580>].

In [ ]:
weights , biases = hidden1.get_weights()

In [ ]:
weights

array([[ 0.02448617, -0.00877795, -0.02189048, ..., -0.02766046,
         0.03859074, -0.06889391],
       [ 0.00476504, -0.03105379, -0.0586676 , ...,  0.00602964,
        -0.02763776, -0.04165364],
       [-0.06189284, -0.06901957,  0.07102345, ..., -0.04238207,
         0.07121518, -0.07331658],
       ...,
       [-0.03048757,  0.02155137, -0.05400612, ..., -0.00113463,
         0.00228987,  0.05581069],
       [ 0.07061854, -0.06960931,  0.07038955, ..., -0.00384101,
         0.00034875,  0.02878492],
       [-0.06022581,  0.01577859, -0.02585464, ..., -0.00527829,
         0.00272203, -0.06793761]], dtype=float32)

In [ ]:
biases

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
weights.shape

(784, 300)

In [ ]:
biases.shape

(300,)

In [ ]:
model.compile(loss="sparse_categorical_crossentropy",
optimizer="sgd",
metrics=["accuracy"])

In [ ]:
history = model.fit(X_train, y_train, epochs=30,
validation_data=(X_valid, y_valid))

Epoch 1/30
1719/1719 [==============================] - 9s 5ms/step - loss: 0.7220 - accuracy: 0.7647 - val_loss: 0.4961 - val_accuracy: 0.8328
Epoch 2/30
1719/1719 [==============================] - 8s 4ms/step - loss: 0.4825 - accuracy: 0.8331 - val_loss: 0.4570 - val_accuracy: 0.8382
Epoch 3/30
1719/1719 [==============================] - 8s 5ms/step - loss: 0.4368 - accuracy: 0.8480 - val_loss: 0.4240 - val_accuracy: 0.8540
Epoch 4/30
1719/1719 [==============================] - 8s 4ms/step - loss: 0.4120 - accuracy: 0.8560 - val_loss: 0.3967 - val_accuracy: 0.8612
Epoch 5/30
1719/1719 [==============================] - 9s 5ms/step - loss: 0.3910 - accuracy: 0.8634 - val_loss: 0.3885 - val_accuracy: 0.8610
Epoch 6/30
1719/1719 [==============================] - 8s 4ms/step - loss: 0.3751 - accuracy: 0.8693 - val_loss: 0.3922 - val_accuracy: 0.8616
Epoch 7/30
1719/1719 [==============================] - 6s 4ms/step - loss: 0.3629 - accuracy: 0.8712 - val_loss: 0.3703 - val_accuracy:

In [ ]:

import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px

fig = px.line(
    pd.DataFrame(history.history),
    x=pd.DataFrame(history.history).index,
    y=["loss", "accuracy", "val_loss", "val_accuracy"],
    labels={"x": "Epoch", "y": "Value"},
    line_dash_sequence=["dot", "dash", "solid", "dashdot"],
    color_discrete_sequence=["red", "green", "blue", "yellow"],
    title="Training History",
    template='plotly_dark'
    
)

fig.update_layout(
    xaxis=dict(range=[0, 29], showgrid=True),
    yaxis=dict(range=[0, 1], showgrid=True),
    width=800,
    height=600
)

fig.show()


In [ ]:
model.evaluate(X_test, y_test)

313/313 [==============================] - 0s 1ms/step - loss: 0.3253 - accuracy: 0.8835


[0.3253277540206909, 0.8834999799728394]

In [71]:
X_new = X_test[:3]

In [72]:
y_pred = model.predict(X_new)
y_pred.round(2)

array([[0.16, 0.14, 0.06, 0.06, 0.09, 0.16, 0.12, 0.05, 0.1 , 0.06],
       [0.18, 0.22, 0.02, 0.01, 0.05, 0.18, 0.24, 0.03, 0.05, 0.02],
       [0.18, 0.18, 0.05, 0.06, 0.06, 0.18, 0.13, 0.04, 0.08, 0.04]],
      dtype=float32)

In [73]:
import numpy as np 

y_pre = y_pred.argmax(axis=1)
y_pre

array([5, 6, 0], dtype=int64)

In [74]:
np.array(class_names)[y_pre]

array(['Sandal', 'Shirt', 'T-shirt/top'], dtype='<U11')